import { getCountries } from 'libphonenumber-js/max';
import placeTypes from './place-types.json' with { type: 'json' };
import { categoryKey, categoryAliases } from '../shared/categorySearch.js';

const names = new Intl.DisplayNames(['en'], { type: 'region' });
export const countries = getCountries()
  .map((code) => ({ code, name: names.of(code) }))
  .filter((c) => c.name && c.name !== c.code)
  .sort((a, b) => a.name.localeCompare(b.name));
export const countryName = (code) => countries.find((c) => c.code === code)?.name || code;

// Countries where a mobile number is treated as a likely WhatsApp contact and weighted higher.
export const WHATSAPP_FIRST = new Set(['OM']);

const H = 'high', M = 'medium', L = 'low';

// [id, label, Places text query, value]. value = typical budget/need for a website project; drives the
// "category value" score factor. Keep existing ids and labels stable — saved scans refer to them.
const GROUPS = {
  'Health & medical': [
    ['dentist', 'Dentists', 'dental clinic', H],
    ['orthodontist', 'Orthodontists', 'orthodontist', H],
    ['clinic', 'Medical clinics', 'medical clinic', H],
    ['hospital', 'Hospitals', 'hospital', H],
    ['doctor', 'Doctors', 'doctor', H],
    ['dermatologist', 'Dermatology clinics', 'dermatology clinic', H],
    ['aesthetic_clinic', 'Cosmetic & aesthetic clinics', 'aesthetic clinic', H],
    ['plastic_surgeon', 'Plastic surgeons', 'plastic surgeon', H],
    ['laser_hair_removal', 'Laser hair removal clinics', 'laser hair removal clinic', H],
    ['eye_clinic', 'Eye clinics', 'eye clinic', H],
    ['optician', 'Opticians', 'optician', M],
    ['physiotherapy', 'Physiotherapy centres', 'physiotherapy center', H],
    ['chiropractor', 'Chiropractors', 'chiropractor', H],
    ['pediatrician', 'Paediatric clinics', 'pediatric clinic', H],
    ['gynecologist', 'Gynaecology clinics', 'gynecology clinic', H],
    ['fertility_clinic', 'Fertility & IVF clinics', 'IVF fertility clinic', H],
    ['psychologist', 'Psychologists & counsellors', 'psychologist', H],
    ['medical_lab', 'Medical laboratories', 'medical laboratory', H],
    ['diagnostic_center', 'Diagnostic & imaging centres', 'diagnostic imaging center', H],
    ['home_healthcare', 'Home healthcare services', 'home healthcare service', H],
    ['medical_supply', 'Medical equipment suppliers', 'medical equipment supplier', H],
    ['pharmacy', 'Pharmacies', 'pharmacy', M],
    ['hearing_aid', 'Hearing aid centres', 'hearing aid center', M],
    ['nutritionist', 'Nutritionists & dietitians', 'nutritionist', M],
    ['alternative_medicine', 'Alternative medicine clinics', 'alternative medicine clinic', M],
  ],
  'Beauty & wellness': [
    ['beauty_salon', 'Beauty salons', 'beauty salon', M],
    ['hair_salon', 'Hair salons', 'hair salon', M],
    ['nail_salon', 'Nail salons', 'nail salon', M],
    ['bridal_salon', 'Bridal salons', 'bridal salon', M],
    ['makeup_artist', 'Makeup artists', 'makeup artist', M],
    ['spa', 'Spas', 'spa', M],
    ['massage', 'Massage centres', 'massage center', M],
    ['barber', 'Barbers', 'barber shop', L],
    ['yoga', 'Yoga studios', 'yoga studio', M],
    ['pilates', 'Pilates studios', 'pilates studio', M],
    ['weight_loss', 'Weight loss centres', 'weight loss center', M],
    ['tattoo', 'Tattoo & henna studios', 'henna tattoo studio', L],
  ],
  'Food & drink': [
    ['restaurant', 'Restaurants', 'restaurant', M],
    ['fine_dining', 'Fine dining restaurants', 'fine dining restaurant', H],
    ['cafe', 'Cafés', 'cafe', M],
    ['coffee_roaster', 'Coffee roasters', 'coffee roaster', M],
    ['bakery', 'Bakeries', 'bakery', M],
    ['catering', 'Catering services', 'catering service', H],
    ['meal_plan', 'Healthy meal-plan delivery', 'healthy meal plan delivery', M],
    ['cloud_kitchen', 'Cloud kitchens', 'cloud kitchen', M],
    ['fast_food', 'Fast food restaurants', 'fast food restaurant', L],
    ['pizza', 'Pizza restaurants', 'pizza restaurant', M],
    ['burger', 'Burger restaurants', 'burger restaurant', M],
    ['seafood_restaurant', 'Seafood restaurants', 'seafood restaurant', M],
    ['steakhouse', 'Steakhouses', 'steakhouse', M],
    ['arabic_restaurant', 'Arabic restaurants', 'arabic restaurant', M],
    ['lebanese_restaurant', 'Lebanese restaurants', 'lebanese restaurant', M],
    ['turkish_restaurant', 'Turkish restaurants', 'turkish restaurant', M],
    ['indian_restaurant', 'Indian restaurants', 'indian restaurant', M],
    ['pakistani_restaurant', 'Pakistani restaurants', 'pakistani restaurant', M],
    ['chinese_restaurant', 'Chinese restaurants', 'chinese restaurant', M],
    ['japanese_restaurant', 'Japanese & sushi restaurants', 'japanese sushi restaurant', M],
    ['thai_restaurant', 'Thai restaurants', 'thai restaurant', M],
    ['italian_restaurant', 'Italian restaurants', 'italian restaurant', M],
    ['mexican_restaurant', 'Mexican restaurants', 'mexican restaurant', M],
    ['buffet', 'Buffet restaurants', 'buffet restaurant', M],
    ['bar', 'Bars & lounges', 'bar lounge', M],
    ['shisha', 'Shisha lounges', 'shisha lounge', M],
    ['chocolate', 'Chocolate shops', 'chocolate shop', M],
    ['shawarma', 'Shawarma shops', 'shawarma', L],
    ['juice_bar', 'Juice bars', 'juice bar', L],
    ['dessert', 'Ice cream & dessert shops', 'dessert shop', L],
    ['sweets', 'Sweet & halwa shops', 'sweets shop', L],
    ['tea_house', 'Tea & karak shops', 'tea shop', L],
    ['food_truck', 'Food trucks', 'food truck', L],
  ],
  'Shopping & retail': [
    ['shopping_mall', 'Shopping malls', 'shopping mall', H],
    ['jewelry', 'Jewellery stores', 'jewelry store', H],
    ['kitchen_showroom', 'Kitchen & bathroom showrooms', 'kitchen showroom', H],
    ['clothing', 'Clothing boutiques', 'clothing boutique', M],
    ['abaya', 'Abaya shops', 'abaya shop', M],
    ['shoe_store', 'Shoe stores', 'shoe store', M],
    ['watch_store', 'Watch stores', 'watch store', M],
    ['perfume_store', 'Perfume & oud shops', 'perfume shop', M],
    ['frankincense', 'Frankincense & incense shops', 'frankincense shop', M],
    ['cosmetics_store', 'Cosmetics stores', 'cosmetics store', M],
    ['electronics', 'Electronics stores', 'electronics store', M],
    ['computer_store', 'Computer stores', 'computer store', M],
    ['furniture', 'Furniture stores', 'furniture store', M],
    ['home_decor', 'Home décor stores', 'home decor store', M],
    ['curtains', 'Curtain & blinds shops', 'curtains shop', M],
    ['carpet', 'Carpet & rug stores', 'carpet store', M],
    ['lighting', 'Lighting stores', 'lighting store', M],
    ['appliances', 'Home appliance stores', 'home appliance store', M],
    ['garden_center', 'Garden centres & nurseries', 'plant nursery', M],
    ['florist', 'Florists', 'florist', M],
    ['gift_shop', 'Gift shops', 'gift shop', M],
    ['handicrafts', 'Handicraft & souvenir shops', 'souvenir shop', M],
    ['toy_store', 'Toy stores', 'toy store', M],
    ['baby_store', 'Baby stores', 'baby store', M],
    ['sports_store', 'Sports shops', 'sporting goods store', M],
    ['bicycle', 'Bicycle shops', 'bicycle shop', M],
    ['music_store', 'Musical instrument stores', 'musical instrument store', M],
    ['supermarket', 'Supermarkets', 'supermarket', M],
    ['organic_store', 'Organic & health food stores', 'organic food store', M],
    ['dates_shop', 'Dates shops', 'dates shop', M],
    ['honey_shop', 'Honey shops', 'honey shop', M],
    ['department_store', 'Department stores', 'department store', M],
    ['wholesale', 'Wholesalers', 'wholesaler', M],
    ['mobile_phone', 'Mobile phone shops', 'mobile phone shop', L],
    ['hardware', 'Hardware stores', 'hardware store', L],
    ['paint_store', 'Paint stores', 'paint store', L],
    ['bookstore', 'Bookstores', 'bookstore', L],
    ['stationery', 'Stationery shops', 'stationery shop', L],
    ['grocery', 'Grocery stores', 'grocery store', L],
    ['convenience_store', 'Convenience stores', 'convenience store', L],
    ['butcher', 'Butchers', 'butcher shop', L],
    ['fish_market', 'Fish shops', 'fish shop', L],
    ['spice_shop', 'Spice & nut shops', 'spice shop', L],
    ['fabric_store', 'Fabric & textile shops', 'fabric store', L],
    ['tailor', 'Tailors', 'tailor', L],
    ['luggage', 'Bag & luggage stores', 'luggage store', L],
    ['vape_shop', 'Tobacco & vape shops', 'vape shop', L],
    ['second_hand', 'Second-hand stores', 'second hand store', L],
  ],
  Automotive: [
    ['car_dealer', 'Car dealers', 'car dealer', H],
    ['used_car', 'Used car dealers', 'used car dealer', H],
    ['car_rental', 'Car rental agencies', 'car rental', H],
    ['motorcycle_dealer', 'Motorcycle dealers', 'motorcycle dealer', H],
    ['boat_dealer', 'Boat dealers & marinas', 'boat dealer', H],
    ['heavy_equipment', 'Heavy equipment rental', 'heavy equipment rental', H],
    ['car_repair', 'Car repair & garages', 'car repair', M],
    ['auto_body', 'Body shops & car paint', 'auto body shop', M],
    ['car_detailing', 'Car detailing & polishing', 'car detailing', M],
    ['car_tinting', 'Window tinting & PPF', 'car window tinting', M],
    ['auto_parts', 'Auto parts stores', 'auto parts store', M],
    ['car_accessories', 'Car accessories shops', 'car accessories shop', M],
    ['driving_school', 'Driving schools', 'driving school', M],
    ['towing', 'Towing & recovery', 'towing service', M],
    ['car_wash', 'Car washes', 'car wash', L],
    ['tyre_shop', 'Tyre shops', 'tire shop', L],
  ],
  'Real estate & construction': [
    ['real_estate', 'Real estate agencies', 'real estate agency', H],
    ['property_developer', 'Property developers', 'property developer', H],
    ['property_management', 'Property management companies', 'property management company', H],
    ['construction', 'Construction companies', 'construction company', H],
    ['contractor', 'General contractors', 'general contractor', H],
    ['interior', 'Interior designers', 'interior design company', H],
    ['architect', 'Architects', 'architecture firm', H],
    ['engineering', 'Engineering consultants', 'engineering consultant', H],
    ['landscaping', 'Landscaping companies', 'landscaping company', H],
    ['swimming_pool', 'Swimming pool contractors', 'swimming pool contractor', H],
    ['solar', 'Solar energy companies', 'solar energy company', H],
    ['building_materials', 'Building materials suppliers', 'building materials supplier', H],
    ['ac_repair', 'AC repair & HVAC', 'air conditioning repair', M],
    ['electrician', 'Electricians', 'electrician', M],
    ['plumber', 'Plumbers', 'plumber', M],
    ['carpenter', 'Carpentry & joinery', 'carpentry workshop', M],
    ['aluminium', 'Aluminium & glass works', 'aluminium and glass works', M],
    ['steel_fabrication', 'Steel fabrication', 'steel fabrication', M],
    ['painter', 'Painting contractors', 'painting contractor', M],
    ['flooring', 'Flooring & tiles', 'flooring company', M],
    ['waterproofing', 'Roofing & waterproofing', 'waterproofing company', M],
  ],
  'Contractors & heavy equipment': [
    ['building_contractor', 'Building contractors', 'building contractor', H],
    ['commercial_contractor', 'Commercial contractors', 'commercial construction contractor', H],
    ['local_contractor', 'Local contractors', 'local contractor', H],
    ['residential_contractor', 'Residential contractors', 'residential contractor', H],
    ['renovation_contractor', 'Renovation contractors', 'renovation contractor', H],
    ['home_improvement_contractor', 'Home improvement contractors', 'home improvement contractor', H],
    ['earthwork_contractor', 'Earthwork contractors', 'earthwork contractor', H],
    ['excavation_contractor', 'Excavation contractors', 'excavation contractor', H],
    ['demolition_contractor', 'Demolition contractors', 'demolition contractor', H],
    ['grading_contractor', 'Grading contractors', 'grading contractor', H],
    ['site_preparation_contractor', 'Site preparation contractors', 'site preparation contractor', H],
    ['paving_contractor', 'Paving contractors', 'paving contractor', H],
    ['asphalt_contractor', 'Asphalt contractors', 'asphalt contractor', H],
    ['road_contractor', 'Road & highway contractors', 'road construction contractor', H],
    ['bridge_contractor', 'Bridge contractors', 'bridge construction contractor', H],
    ['concrete_contractor', 'Concrete contractors', 'concrete contractor', H],
    ['utility_contractor', 'Utility contractors', 'utility contractor', H],
    ['underground_utility_contractor', 'Underground utility contractors', 'underground utility contractor', H],
    ['sewer_water_contractor', 'Sewer & water contractors', 'sewer and water contractor', H],
    ['pipeline_contractor', 'Pipeline contractors', 'pipeline contractor', H],
    ['power_line_contractor', 'Power line contractors', 'power line contractor', H],
    ['industrial_contractor', 'Industrial contractors', 'industrial contractor', H],
    ['mechanical_contractor', 'Mechanical contractors', 'mechanical contractor', H],
    ['electrical_contractor', 'Electrical contractors', 'electrical contractor', H],
    ['plumbing_contractor', 'Plumbing contractors', 'plumbing contractor', H],
    ['hvac_contractor', 'HVAC contractors', 'HVAC contractor', H],
    ['roofing_contractor', 'Roofing contractors', 'roofing contractor', H],
    ['fencing_contractor', 'Fencing contractors', 'fencing contractor', M],
    ['land_clearing_contractor', 'Land-clearing contractors', 'land clearing contractor', H],
    ['forestry_contractor', 'Forestry contractors', 'forestry contractor', H],
    ['logging_contractor', 'Logging contractors', 'logging contractor', H],
    ['timber_harvesting', 'Timber harvesting companies', 'timber harvesting company', H],
    ['mining_contractor', 'Mining contractors', 'mining contractor', H],
    ['heavy_equipment_dealer', 'Heavy equipment dealers', 'heavy equipment dealer', H],
    ['heavy_equipment_repair', 'Heavy equipment repair', 'heavy equipment repair', H],
    ['heavy_equipment_parts', 'Heavy equipment parts suppliers', 'heavy equipment parts supplier', M],
    ['construction_equipment_rental', 'Construction equipment rental', 'construction equipment rental', H],
    ['crane_rental', 'Crane rental & lifting services', 'crane rental service', H],
    ['equipment_transport', 'Heavy equipment transport', 'heavy equipment transport', M],
    ['aggregate_supplier', 'Aggregate suppliers', 'aggregate supplier', H],
    ['quarry', 'Quarries', 'quarry', H],
    ['sand_gravel_supplier', 'Sand & gravel suppliers', 'sand gravel supplier', H],
    ['ready_mix_concrete', 'Ready-mix concrete suppliers', 'ready mix concrete supplier', H],
    ['asphalt_plant', 'Asphalt plants', 'asphalt plant', H],
    ['oilfield_services', 'Oilfield services', 'oilfield services company', H],
    ['tree_service', 'Tree service & arborists', 'tree service arborist', M],
    ['welding_fabrication', 'Welding & fabrication shops', 'welding fabrication shop', M],
  ],
  'Security & surveillance': [
    ['local_security_services', 'Local security companies', 'security services company', M],
    ['security_systems', 'CCTV & security systems', 'cctv installation', M],
    ['security_camera_installation', 'Security camera installers', 'security camera installation company', M],
    ['cctv_monitoring', 'CCTV monitoring companies', 'CCTV monitoring company', M],
    ['remote_video_monitoring', 'Remote video monitoring', 'remote video monitoring company', M],
    ['live_video_monitoring', 'Live video monitoring', 'live video monitoring service', M],
    ['video_surveillance', 'Video surveillance companies', 'video surveillance company', M],
    ['remote_guarding', 'Remote guarding & virtual guards', 'remote guarding service', M],
    ['alarm_monitoring', 'Alarm monitoring companies', 'alarm monitoring company', M],
    ['burglar_alarm_installation', 'Burglar alarm installers', 'burglar alarm installation', M],
    ['commercial_security', 'Commercial security systems', 'commercial security systems company', M],
    ['home_security', 'Home security & smart alarms', 'home security system installation', M],
    ['access_control', 'Access control & biometric systems', 'access control system installation', M],
    ['intercom_installation', 'Intercom & video door entry', 'video intercom installation', M],
    ['fire_alarm_installation', 'Fire alarms & safety systems', 'fire alarm installation company', M],
    ['security_system_maintenance', 'Security system repair & maintenance', 'CCTV security system repair maintenance', M],
    ['security_equipment_supplier', 'CCTV & security equipment suppliers', 'security camera equipment supplier', M],
    ['mobile_surveillance', 'Mobile surveillance & CCTV towers', 'mobile surveillance trailer company', M],
    ['construction_site_security', 'Construction site security', 'construction site security company', M],
    ['security_company', 'Security guard companies', 'security company', M],
    ['security_patrol', 'Security patrol services', 'mobile security patrol service', M],
    ['security_consulting', 'Security consultants & risk assessments', 'physical security consultant', M],
  ],
  'Hotels & travel': [
    ['hotel', 'Hotels', 'hotel', H],
    ['resort', 'Resorts', 'resort', H],
    ['serviced_apartments', 'Serviced apartments', 'serviced apartments', H],
    ['desert_camp', 'Desert camps & glamping', 'desert camp', H],
    ['tour_operator', 'Tour operators', 'tour operator', H],
    ['event_venue', 'Event venues', 'event venue', H],
    ['wedding_hall', 'Wedding halls', 'wedding hall', H],
    ['guest_house', 'Guest houses', 'guest house', M],
    ['travel_agency', 'Travel agencies', 'travel agency', M],
    ['hostel', 'Hostels', 'hostel', L],
  ],
  'Professional & business services': [
    ['lawyer', 'Law firms', 'law firm', H],
    ['accounting', 'Accountants', 'accounting firm', H],
    ['consultant', 'Business consultants', 'business consultant', H],
    ['marketing', 'Marketing agencies', 'marketing agency', H],
    ['advertising', 'Advertising agencies', 'advertising agency', H],
    ['it_company', 'IT companies', 'IT company', H],
    ['software', 'Software companies', 'software company', H],
    ['insurance', 'Insurance agencies', 'insurance agency', H],
    ['financial_advisor', 'Financial advisors', 'financial advisor', H],
    ['recruitment', 'Recruitment agencies', 'recruitment agency', H],
    ['logistics', 'Logistics & freight companies', 'logistics company', H],
    ['import_export', 'Import & export companies', 'import export company', H],
    ['oil_gas_services', 'Oil & gas services', 'oil and gas services company', H],
    ['facility_management', 'Facility management', 'facility management company', H],
    ['event_planner', 'Event planners', 'event planner', H],
    ['wedding_planner', 'Wedding planners', 'wedding planner', H],
    ['web_design', 'Web design agencies', 'web design company', M],
    ['printing', 'Printing presses', 'printing press', M],
    ['signage', 'Sign makers', 'sign company', M],
    ['photographer', 'Photographers & photo studios', 'photography studio', M],
    ['video_production', 'Video production', 'video production company', M],
    ['manpower', 'Manpower agencies', 'manpower supply company', M],
    ['pro_services', 'PRO & visa services', 'PRO services', M],
    ['translation', 'Translation services', 'translation office', M],
    ['money_exchange', 'Money exchanges', 'money exchange', M],
    ['courier', 'Courier services', 'courier service', M],
    ['movers', 'Movers & packers', 'moving company', M],
    ['cleaning', 'Cleaning companies', 'cleaning service', M],
    ['pest_control', 'Pest control', 'pest control', M],
    ['coworking', 'Coworking spaces', 'coworking space', M],
    ['trading', 'Trading companies', 'trading company', M],
    ['computer_repair', 'Computer & laptop repair', 'computer repair', M],
    ['appliance_repair', 'Appliance repair', 'appliance repair', M],
    ['phone_repair', 'Phone repair shops', 'phone repair shop', L],
    ['laundry', 'Laundries', 'laundry', L],
    ['dry_cleaning', 'Dry cleaners', 'dry cleaner', L],
  ],
  'Education & childcare': [
    ['school', 'Training centres & schools', 'training center', H],
    ['private_school', 'Private schools', 'private school', H],
    ['nursery', 'Nurseries & kindergartens', 'kindergarten', H],
    ['university', 'Universities & colleges', 'college', H],
    ['language_school', 'Language institutes', 'language institute', H],
    ['computer_training', 'IT training institutes', 'computer training institute', H],
    ['tutoring', 'Tutoring centres', 'tutoring center', M],
    ['music_school', 'Music schools', 'music school', M],
    ['art_school', 'Art & craft classes', 'art school', M],
    ['dance_school', 'Dance studios', 'dance studio', M],
    ['daycare', 'Daycare centres', 'day care center', M],
    ['special_needs', 'Special needs centres', 'special needs center', M],
    ['quran_school', 'Quran centres', 'quran center', L],
  ],
  'Sports & leisure': [
    ['gym', 'Gyms & fitness', 'gym', M],
    ['golf', 'Golf clubs', 'golf club', H],
    ['diving', 'Diving centres', 'dive center', H],
    ['horse_riding', 'Horse riding stables', 'horse riding', H],
    ['water_sports', 'Water sports & boat tours', 'boat tour', H],
    ['martial_arts', 'Martial arts academies', 'martial arts academy', M],
    ['swimming_school', 'Swimming schools', 'swimming lessons', M],
    ['football_academy', 'Football academies', 'football academy', M],
    ['sports_club', 'Sports clubs', 'sports club', M],
    ['padel', 'Padel & tennis courts', 'padel court', M],
    ['kids_play', 'Kids play areas', 'kids play area', M],
    ['amusement', 'Arcades & amusement centres', 'amusement center', M],
    ['escape_room', 'Escape rooms', 'escape room', M],
    ['art_gallery', 'Art galleries', 'art gallery', M],
    ['recording_studio', 'Recording studios', 'recording studio', M],
    ['framing', 'Picture framing shops', 'picture framing', L],
  ],
  Pets: [
    ['veterinary', 'Veterinary clinics', 'veterinary clinic', M],
    ['pet_store', 'Pet shops', 'pet shop', M],
    ['pet_grooming', 'Pet grooming', 'pet grooming', M],
    ['pet_boarding', 'Pet boarding & kennels', 'pet boarding', M],
    ['aquarium_shop', 'Aquarium & fish shops', 'aquarium shop', L],
  ],
  Community: [
    ['charity', 'Charities & non-profits', 'charity organization', M],
  ],
};

export const curatedCategories = Object.entries(GROUPS)
  .flatMap(([group, list]) => list.map(([id, label, query, value]) => ({ id, label, query, value, group })));

const groupNames = { Business: 'Professional & business services', Culture: 'Arts & culture', Education: 'Education & childcare', 'Entertainment and Recreation': 'Sports & leisure', Finance: 'Finance', 'Food and Drink': 'Food & drink', 'Health and Wellness': 'Health & medical', Housing: 'Real estate & construction', Lodging: 'Hotels & travel', 'Places of Worship': 'Community', Shopping: 'Shopping & retail', Sports: 'Sports & leisure', Services: 'Services', Transportation: 'Transport', Government: 'Community', Facilities: 'Community' };
const existingQueries = new Set(curatedCategories.flatMap(row => [categoryKey(row.query), categoryKey(row.label)]));
const additionalTypes = placeTypes.types.filter(row => !['Geographical Areas', 'Natural Features'].includes(row.group) && !existingQueries.has(categoryKey(row.type)));
export const categories = [...curatedCategories.map(row => ({ ...row, source: 'curated' })), ...additionalTypes.map(({ type, group }) => ({
  id: `places:${type}`, label: type.replaceAll('_', ' ').replace(/^./, char => char.toUpperCase()), query: type.replaceAll('_', ' '),
  value: 'medium', group: groupNames[group] || group, source: 'places', placesType: type,
}))].map(row => ({ ...row, aliases: categoryAliases(row) }));
export const categorySnapshot = { source: placeTypes.source, retrievedAt: placeTypes.retrievedAt, count: categories.length };

// Google place types where online booking/ordering is expected.
export const BOOKABLE_TYPES = new Set(['restaurant', 'cafe', 'dentist', 'doctor', 'beauty_salon', 'spa', 'gym',
  'hotel', 'lodging', 'car_repair', 'veterinary_care', 'hair_care', 'meal_delivery', 'meal_takeaway', 'bakery']);
