const keyField = (label = 'API key') => ({ name: 'apiKey', label, secret: true });
const googleFields = [{ name: 'serviceAccount', label: 'Service account JSON', secret: true, multiline: true }];
export const INTEGRATIONS = [
  { id: 'openai', name: 'OpenAI', category: 'AI', description: 'GPT', fields: [keyField()], help: 'Use an OpenAI API key. Connect checks available models.', docs: 'https://platform.openai.com/api-keys' },
  { id: 'gemini', name: 'Google Gemini', category: 'AI', description: 'Gemini', fields: [keyField()], help: 'Use a Gemini API key from Google AI Studio.', docs: 'https://aistudio.google.com/api-keys' },
  { id: 'telnyx', name: 'Telnyx', category: 'Messaging', description: 'SMS', fields: [keyField(), { name: 'fromNumber', label: 'Telnyx phone number', placeholder: '+14155550123' }], help: 'Use your API key and an SMS-enabled Telnyx number assigned to a messaging profile.', docs: 'https://portal.telnyx.com/' },
  { id: 'vonage', name: 'Vonage', category: 'Messaging', description: 'SMS', fields: [keyField(), { name: 'apiSecret', label: 'API secret', secret: true }, { name: 'fromNumber', label: 'Sender number', placeholder: '+14155550123' }], help: 'Use your API key, API secret, and a registered SMS sender number. Availability depends on the destination country.', docs: 'https://dashboard.nexmo.com/' },
  { id: 'neverbounce', name: 'NeverBounce', category: 'Data', description: 'Email verification', fields: [keyField()], help: 'Use a NeverBounce API key. Connect checks your account without verifying any addresses.', docs: 'https://developers.neverbounce.com/reference/account-info' },
  { id: 'apollo', name: 'Apollo', category: 'Data', description: 'Contact enrichment', fields: [keyField()], help: 'Use an Apollo API key. Connect checks authentication without using enrichment credits.', docs: 'https://docs.apollo.io/reference/authentication' },
  { id: 'anthropic', name: 'Anthropic', category: 'AI', description: 'Claude', fields: [keyField()], help: 'Use a Claude API key. Connect checks model access without generating content.', docs: 'https://platform.claude.com/settings/keys' },
  { id: 'slack', name: 'Slack', category: 'Messaging', description: 'Team workspace', fields: [keyField('Bot token')], help: 'Use a bot token from your installed Slack app. Connect checks the workspace identity.', docs: 'https://api.slack.com/apps' },
  { id: 'google-docs', name: 'Google Docs', category: 'Documents', description: 'Documents', fields: [...googleFields, { name: 'resourceId', label: 'Document ID' }], help: 'Enable the Google Docs API. Share the document with the client_email in your service account JSON, then paste its ID from the document URL. Access is read-only.', docs: 'https://developers.google.com/workspace/docs/api/quickstart' },
  { id: 'google-sheets', name: 'Google Sheets', category: 'Documents', description: 'Spreadsheets', fields: [...googleFields, { name: 'resourceId', label: 'Spreadsheet ID' }], help: 'Enable the Google Sheets API. Share the spreadsheet with the client_email in your service account JSON, then paste its ID from the spreadsheet URL. Access is read-only.', docs: 'https://developers.google.com/workspace/sheets/api/quickstart' },
  { id: 'google-drive', name: 'Google Drive', category: 'Documents', description: 'Files', fields: googleFields, help: 'Enable the Google Drive API. Paste your service account JSON. Only files shared with that service account are accessible. Access is read-only.', docs: 'https://developers.google.com/workspace/drive/api/quickstart' },
  { id: 'hubspot', name: 'HubSpot', category: 'Data', description: 'CRM', fields: [keyField('Private app token')], help: 'Use a HubSpot private app token. Connect checks your account identity.', docs: 'https://developers.hubspot.com/docs/apps/legacy-apps/private-apps/overview' },
  { id: 'twilio', name: 'Twilio', category: 'Messaging', description: 'SMS', fields: [{ name: 'accountSid', label: 'Account SID' }, { name: 'authToken', label: 'Auth token', secret: true }, { name: 'fromNumber', label: 'Twilio phone number', placeholder: '+14155550123' }], help: 'Use your Twilio Account SID, auth token, and an SMS-capable number you own. Trial accounts can only send to verified recipients.', docs: 'https://console.twilio.com/' },
  { id: 'firecrawl', name: 'Firecrawl', category: 'Data', description: 'Web crawl & scrape', fields: [keyField()], help: 'Use a Firecrawl API key. Connect checks API access and team credit usage.', docs: 'https://docs.firecrawl.dev' },
];
