import { useEffect, useState } from 'react';
import { api, fmt, qs } from '../lib/api.js';
import { Icon, Kpi, PageHead } from './ui.jsx';
import ProviderIcon from './ProviderIcon.jsx';

const TITLES = {domain:['Domain & DNS','Give every message a trusted sender.'],verification:['Email verification','Check an address before reaching out.'],rules:['Sending rules','A steady pace. Clear boundaries.'],suppression:['Do not contact','Keep every opt-out respected.'],history:['Email activity','Know exactly what happened.']};
const STATUS = {found:'Record found',missing:'Missing',issue:'Needs attention',unknown:'Not determined',not_checked:'Not checked',domain_valid:'Domain has a mail route',deliverable:'Mailbox reported deliverable',invalid:'Invalid',risky:'Risk flagged',sent:'Accepted by provider',failed:'Not sent',sending:'Sending',paused:'Paused'};
function Status({value}) { return <span className={`email-status-badge email-status-${value}`}>{STATUS[value] || value}</span>; }

export default function EmailInfrastructure({section,accountId,notify,onDirtyChange,onBusyChange}) {
  const [config,setConfig]=useState(null),[savedConfig,setSavedConfig]=useState(null),[policy,setPolicy]=useState(null),[savedPolicy,setSavedPolicy]=useState(null);
  const [rows,setRows]=useState([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
  const [audit,setAudit]=useState(null),[plan,setPlan]=useState(null),[address,setAddress]=useState(''),[reason,setReason]=useState('opt_out');
  const [verification,setVerification]=useState(null),[apiKey,setApiKey]=useState('');
  useEffect(()=>{onBusyChange?.(Boolean(busy));return()=>onBusyChange?.(false);},[busy,onBusyChange]);
  const dirty=Boolean(apiKey)||(section==='domain'&&JSON.stringify(config)!==JSON.stringify(savedConfig))||(section==='rules'&&JSON.stringify(policy)!==JSON.stringify(savedPolicy));
  useEffect(()=>{onDirtyChange?.(dirty||Boolean(busy));},[dirty,busy,onDirtyChange]);
  useEffect(()=>()=>onDirtyChange?.(false),[onDirtyChange]);
  useEffect(()=>{ const guard=(e)=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,busy]);
  useEffect(()=>{
    let off=false;setLoading(true);setError('');setAudit(null);setPlan(null);setVerification(null);
    const endpoint=section==='domain'||section==='verification'?'/email/infrastructure':section==='rules'?'/email/policy':section==='suppression'?'/email/suppressions':`/email/messages${qs({accountId})}`;
    api.get(endpoint).then(data=>{if(off)return;if(section==='domain'||section==='verification'){setConfig(data);setSavedConfig(data);}else if(section==='rules'){setPolicy(data);setSavedPolicy(data);}else setRows(data.rows||[]);}).catch(e=>{if(!off)setError(e.message);}).finally(()=>{if(!off)setLoading(false);});return()=>{off=true;};
  },[section,accountId]);
  async function run(name,fn) {if(busy)return;setBusy(name);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy('');}}
  const change=(key,value)=>{setConfig(c=>({...c,[key]:value}));setPlan(null);setAudit(null);};
  async function saveDomain(){const next=await api.put('/email/infrastructure',config);setConfig(next);setSavedConfig(next);notify('Domain setup saved','success');return next;}
  async function copy(value){try{await navigator.clipboard.writeText(value);notify('Copied','success');}catch{notify('Select the record text and copy it manually.','error');}}
  async function refreshRows(){const data=await api.get(section==='suppression'?'/email/suppressions':`/email/messages${qs({accountId})}`);setRows(data.rows||[]);}
  const [title,description]=TITLES[section];
  return <div className="page email-infrastructure">
    <PageHead eyebrow="Local Geni / Email" title={title}/>
    {error&&<div className="banner error" role="alert">{error}</div>}
    {loading?<div className="card loading">Loading...</div>:<>
      {section==='domain'&&config&&<>
        <section className="card form">
          <div className="card-head"><h3>Sending domain</h3><span className="hint">Live DNS</span></div>
          <div className="field-row"><label className="field grow"><span>Domain you own</span><input value={config.domain} onChange={e=>change('domain',e.target.value)} placeholder="youragency.com" disabled={Boolean(busy)}/></label><label className="field"><span>Email provider</span><select value={config.provider} onChange={e=>change('provider',e.target.value)} disabled={Boolean(busy)}><option value="gmail">Google Workspace</option><option value="microsoft">Microsoft 365</option><option value="smtp">Other provider / SMTP</option></select></label></div>
          <div className="field-row"><label className="field grow"><span>DKIM selector</span><input value={config.selector} onChange={e=>change('selector',e.target.value)} placeholder="Your provider’s selector" disabled={Boolean(busy)}/><small>Use the selector from your provider’s admin console. A selector is required to find its public key.</small></label>{config.provider==='smtp'&&<label className="field grow"><span>SPF include from your provider</span><input value={config.spfInclude} onChange={e=>change('spfInclude',e.target.value)} placeholder="spf.mail-provider.com" disabled={Boolean(busy)}/></label>}</div>
          <div className="field-row"><label className="field"><span>DMARC draft policy</span><select value={config.dmarcPolicy} onChange={e=>change('dmarcPolicy',e.target.value)} disabled={Boolean(busy)}><option value="none">Monitor (none)</option><option value="quarantine">Quarantine</option><option value="reject">Reject</option></select></label><label className="field grow"><span>DMARC report mailbox <em>optional</em></span><input type="email" value={config.reportAddress} onChange={e=>change('reportAddress',e.target.value)} placeholder="dmarc@youragency.com" disabled={Boolean(busy)}/></label></div>
          <div className="preview-actions"><button className="btn" disabled={Boolean(busy)||!dirty} onClick={()=>run('save',saveDomain)}>Save setup</button><button className="btn primary" disabled={Boolean(busy)||!config.domain} onClick={()=>run('check',async()=>{const c=await saveDomain();setAudit(await api.post('/email/domain/check',{domain:c.domain,selector:c.selector}));})}>{busy==='check'?'Checking DNS...':'Check SPF, DKIM & DMARC'}</button><button className="btn" disabled={Boolean(busy)||!config.domain} onClick={()=>run('plan',async()=>{await saveDomain();setAudit(await api.post('/email/domain/check',{domain:config.domain,selector:config.selector}));setPlan(await api.get('/email/domain/plan'));})}>Prepare DNS records</button></div>
          <p className="hint">Use a domain you control. Gmail.com and Outlook.com authentication is managed by Google and Microsoft. A DNS record check does not measure inbox placement.</p>
        </section>
        {audit&&<section className="email-dns-grid" aria-label="Domain authentication results">{audit.checks.map(check=><article className="card" key={check.key}><div className="card-head"><h3>{check.label}</h3><Status value={check.status}/></div><p>{check.detail}</p>{check.records.map((record,i)=><code className="email-dns-record" key={i}>{record}</code>)}</article>)}<p className="hint">Checked {new Date(audit.checkedAt).toLocaleString()}. {audit.note}</p></section>}
        {plan&&<section className="card form"><div className="card-head"><h3>DNS record drafts</h3><span className="email-status-badge">Not published</span></div><p className="hint">{plan.note}</p>{plan.records.map((record,i)=><div className="email-dns-draft" key={i}><div className="card-head"><strong>{record.type} / {record.name}</strong>{record.value&&<button className="btn xs" onClick={()=>copy(record.value)}>Copy value</button>}</div><code className="email-dns-record">{record.value||'Resolve existing records first.'}</code><p className="hint">{record.note}</p></div>)}<p className="hint">Publish these in your DNS provider, then run the checks again. Never add a second SPF or DMARC record at the same name.</p></section>}
        <section className="card form"><div className="card-head"><h3>DKIM signing</h3><Status value={config.dkim?.enabled?'found':'not_checked'}/></div>{config.provider!=='smtp'?<><p>Your mailbox provider signs messages. Enable DKIM for your domain in its admin console, then enter the assigned selector above to check its public key.</p><a className="link" target="_blank" rel="noreferrer" href={config.provider==='gmail'?'https://support.google.com/a/answer/180504':'https://learn.microsoft.com/en-us/defender-office-365/email-authentication-dkim-configure'}>Official {config.provider==='gmail'?'Google Workspace':'Microsoft 365'} DKIM setup</a></>:<><p>Create a 2048-bit signing key for messages sent through custom SMTP. Publish its public DNS record before enabling signing. The private key stays encrypted on this Mac.</p>{config.dkim&&<><p className="hint">Key for {config.dkim.domain} / selector {config.dkim.selector}. {config.dkim.enabled?'Signing enabled.':'Signing disabled.'}</p><code className="email-dns-record">{config.dkim.publicRecord}</code><button className="btn" onClick={()=>copy(config.dkim.publicRecord)}>Copy public key record</button></>}<div className="preview-actions"><button className="btn" disabled={Boolean(busy)||!config.domain||config.dkim?.enabled} onClick={()=>{if(config.dkim&&!window.confirm('Replace the inactive DKIM key? Publish the new public key before enabling it.'))return;run('key',async()=>{await saveDomain();const next=await api.post('/email/dkim/generate',{domain:config.domain,selector:config.selector});setConfig(next);setSavedConfig(next);setPlan(await api.get('/email/domain/plan'));});}}>{busy==='key'?'Generating...':config.dkim?'Replace inactive key':'Generate signing key'}</button>{config.dkim&&<button className="btn primary" disabled={Boolean(busy)||dirty} onClick={()=>run('dkim',async()=>{const next=await api.post('/email/dkim/enabled',{enabled:!config.dkim.enabled});setConfig(next);setSavedConfig(next);notify(next.dkim.enabled?'Published key verified. Signing enabled.':'Signing disabled.','success');})}>{config.dkim.enabled?'Disable signing':'Verify DNS & enable signing'}</button>}</div></>}</section>
      </>}
      {section==='verification'&&config&&<>
        <section className="card form"><div className="card-head"><h3>Check an address</h3><span className="hint">No email is sent</span></div><label className="field"><span>Email address</span><input type="email" value={address} onChange={e=>{setAddress(e.target.value);setVerification(null);}} placeholder="owner@business.com" disabled={Boolean(busy)}/></label><div className="preview-actions"><button className="btn" disabled={Boolean(busy)||!address} onClick={()=>run('dns',async()=>setVerification(await api.post('/email/verification',{email:address,mode:'dns',force:true})))}>Check domain</button><button className="btn primary" disabled={Boolean(busy)||!address||!config.verifierConfigured} onClick={()=>run('mailbox',async()=>setVerification(await api.post('/email/verification',{email:address,mode:'mailbox',force:true})))}>{busy==='mailbox'?'Checking mailbox...':'Verify mailbox'}</button></div><p className="hint">Domain checks inspect public DNS. Mailbox checks send the address to your connected ZeroBounce account and may use paid credits.</p>{verification&&<div className="email-verification-result" role="status"><Status value={verification.status}/><p>{verification.summary}</p>{verification.checks.map((c,i)=><p className="hint" key={i}><strong>{c.label}:</strong> {c.detail}</p>)}<p className="hint">{new Date(verification.checkedAt).toLocaleString()}</p></div>}</section>
        <section className="card form"><div className="card-head"><h3 className="provider-label"><ProviderIcon provider="zerobounce" size={20} />ZeroBounce</h3><span className="email-status-badge">{config.verifierConfigured?'Key saved':'Not connected'}</span></div><p>A valid address does not guarantee delivery</p><label className="field"><span>ZeroBounce API key</span><input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={config.verifierConfigured?'Leave blank to keep the saved key':'Enter your API key'} disabled={Boolean(busy)}/></label><div className="preview-actions"><button className="btn primary" disabled={Boolean(busy)||!apiKey} onClick={()=>run('verifier',async()=>{await api.put('/email/verifier',{apiKey});setApiKey('');const next=await api.get('/email/infrastructure');setConfig(next);setSavedConfig(next);notify('Verification key saved','success');})}>Save key</button>{config.verifierConfigured&&<button className="btn" disabled={Boolean(busy)} onClick={()=>run('disconnect',async()=>{await api.put('/email/verifier',{disconnect:true});setConfig(c=>({...c,verifierConfigured:false}));})}>Disconnect</button>}</div></section>
      </>}
      {section==='rules'&&policy&&<>
        <div className="kpis"><Kpi label="Attempts / last 24 hours" value={policy.usage.daily} sub={`Limit ${policy.dailyLimit}`}/><Kpi label="Attempts / last hour" value={policy.usage.hourly} sub={`Limit ${policy.hourlyLimit}`}/><Kpi label="Remaining / rolling 24 hours" value={policy.usage.remainingToday}/><Kpi label="Sending" value={policy.paused?'Paused':policy.usage.nextAllowedAt>Date.now()?'Waiting':'Available'} sub={policy.usage.nextAllowedAt>Date.now()?`Next slot ${new Date(policy.usage.nextAllowedAt).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`:`${policy.minIntervalSeconds}s minimum spacing`}/></div>
        <form className="card form" onSubmit={e=>{e.preventDefault();run('policy',async()=>{const next=await api.put('/email/policy',policy);setPolicy(next);setSavedPolicy(next);notify('Sending rules saved','success');});}}><div className="card-head"><h3>Sending limits</h3><button className="btn primary" disabled={Boolean(busy)||!dirty}>Save rules</button></div><div className="field-row">{[['dailyLimit','Messages per rolling 24 hours',1,1000],['hourlyLimit','Messages per rolling hour',1,100],['minIntervalSeconds','Minimum spacing / seconds',30,3600]].map(([key,label,min,max])=><label className="field grow" key={key}><span>{label}</span><input type="number" required min={min} max={max} step="1" disabled={Boolean(busy)} value={policy[key]} onChange={e=>setPolicy(p=>({...p,[key]:Number(e.target.value)}))}/></label>)}</div><p className="hint">These are local limits, not provider allowances or a promise of inbox delivery. Every attempted send consumes a slot, including failures. Uncertain sends are never retried automatically.</p><label className="check"><input type="checkbox" disabled={Boolean(busy)} checked={policy.paused} onChange={e=>setPolicy(p=>({...p,paused:e.target.checked}))}/>Pause all sending</label><label className="check"><input type="checkbox" disabled={Boolean(busy)} checked={policy.requireMailboxVerification} onChange={e=>setPolicy(p=>({...p,requireMailboxVerification:e.target.checked}))}/>Require a deliverable mailbox check within 30 days</label><label className="check"><input type="checkbox" disabled={Boolean(busy)} checked={policy.requireOptOut} onChange={e=>setPolicy(p=>({...p,requireOptOut:e.target.checked}))}/>Include an opt-out line in every reviewed email</label><label className="field"><span>Opt-out wording</span><textarea rows={3} minLength={10} maxLength={500} required disabled={Boolean(busy)} value={policy.optOutText} onChange={e=>setPolicy(p=>({...p,optOutText:e.target.value}))}/></label><p className="hint">Enable incoming mail for each mailbox to sync replies and bounces. Reviewed sequences stop for matched replies, bounces and opt-outs. Record any opt-out received elsewhere in Do not contact.</p></form>
      </>}
      {section==='suppression'&&<>
        <form className="card form" onSubmit={e=>{e.preventDefault();run('suppress',async()=>{await api.post('/email/suppressions',{email:address,reason});setAddress('');await refreshRows();notify('Address added to Do not contact','success');});}}><div className="card-head"><h3>Add an address</h3><Icon name="lock"/></div><div className="field-row"><label className="field grow"><span>Email address</span><input type="email" value={address} disabled={Boolean(busy)} onChange={e=>setAddress(e.target.value)} required/></label><label className="field"><span>Reason</span><select disabled={Boolean(busy)} value={reason} onChange={e=>setReason(e.target.value)}><option value="opt_out">Opted out</option><option value="bounced">Bounced</option><option value="not_interested">Not interested</option><option value="replied">Already replied</option><option value="manual">Manual block</option></select></label><button className="btn primary" disabled={Boolean(busy)}>Add to Do not contact</button></div><p className="hint">This blocks future sends from Local Geni, across all businesses using the same address.</p></form>
        <section className="card"><div className="card-head"><h3>Do-not-contact list</h3><span className="hint">{rows.length} shown</span></div><label className="field"><span>Find an address</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search email addresses"/></label><div className="table-wrap"><table className="table compact"><thead><tr><th>Address</th><th>Reason</th><th>Added</th><th/></tr></thead><tbody>{rows.filter(r=>r.email.includes(query.toLowerCase())).map(r=><tr key={r.email}><td>{r.email}</td><td>{r.reason.replaceAll('_',' ')}</td><td>{fmt.ago(r.createdAt)}</td><td><button className="btn xs" disabled={Boolean(busy)} onClick={()=>{if(window.confirm(`Allow future contact with ${r.email}? Only remove an opt-out if the person has asked to hear from you again.`))run('remove',async()=>{await api.del(`/email/suppressions/${encodeURIComponent(r.email)}`);await refreshRows();});}}>Allow contact</button></td></tr>)}</tbody></table></div>{!rows.length&&<p className="hint">No blocked addresses</p>}</section>
      </>}
      {section==='history'&&<section className="card form"><div className="card-head"><h3>Send history</h3><button className="btn" disabled={Boolean(busy)} onClick={()=>run('refresh',refreshRows)}>Refresh</button></div><p className="hint">Accepted does not mean delivered or read. Check Sent before resending.</p><label className="field"><span>Search sent messages</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Recipient or subject"/></label><div className="email-history">{rows.filter(r=>`${r.to} ${r.subject}`.toLowerCase().includes(query.toLowerCase())).map(r=><article className="email-history-item" key={r.id}><div className="card-head"><div><strong>{r.subject}</strong><p className="hint">To {r.to} / {new Date(r.createdAt).toLocaleString()}</p></div><Status value={r.status}/></div>{r.error&&<p className="hint bad">{r.error}</p>}<details><summary>View exact email</summary><p className="hint">From {r.fromName} &lt;{r.fromEmail}&gt;</p><pre className="email-review-message">{r.text}</pre></details><div className="preview-actions"><button className="btn xs" disabled={Boolean(busy)} onClick={()=>run('optout',async()=>{await api.post('/email/suppressions',{email:r.to,reason:'opt_out'});notify('Opt-out recorded. Future sends are blocked.','success');})}>Record opt-out</button><button className="btn xs" disabled={Boolean(busy)} onClick={()=>run('bounce',async()=>{await api.post('/email/suppressions',{email:r.to,reason:'bounced'});notify('Bounce recorded. Future sends are blocked.','success');})}>Record bounce</button></div></article>)}</div>{!rows.length&&<div className="email-empty-state"><Icon name="message"/><h3>Your sent emails will appear here.</h3><p>Open a business in Leads, then choose Compose email.</p></div>}</section>}
    </>}
  </div>;
}
